### ISSUE TITLE
One Piece of Working Code

### ISSUE THREAD

**Issue by Swaid-design** [Intro-to-SE-Lab-Fall-20/Group-2#11]
We need to have one piece of working code before the end of sprint 2.

**Comment by Swaid-design** [comment]
I think we could do the login/feature by then end of sprint 2 and start some of the database of the users and admins.

**Comment by bkimball98** [comment]
I shall begin working on this post-hence.

**Comment by elihartnett** [comment]
Spent about 3 hours today looking at different options and trying to understand them. Think PyQt would be a good option for a gui and I have found a great example file you can run to demonstrate what it does and how it works. Screenshot included here
<img width="1273" alt="Screen Shot 2020-09-12 at 3 17 15 PM" src="https://user-images.githubusercontent.com/55256366/93004268-155bbb00-f50b-11ea-989e-e309cb5589ea.png">

**Comment by elihartnett** [comment]
Spent some more time and developed this
<img width="811" alt="Screen Shot 2020-09-13 at 12 53 16 AM" src="https://user-images.githubusercontent.com/55256366/93011404-a490bf00-f55b-11ea-90a9-d4186f88cfb3.png">

**Comment by elihartnett** [comment]
Updated method for producing the UI
<img width="839" alt="Screen Shot 2020-09-14 at 7 34 32 PM" src="https://user-images.githubusercontent.com/55256366/93151618-0a975680-f6c2-11ea-94e4-23ea03ab7b03.png">

**Comment by bkimball98** [comment]
Have you added the code somewhere in the repository? Looks great!

**Comment by elihartnett** [comment]
<img width="702" alt="93945610-e4df0280-fcfc-11ea-9227-caabf175bd59" src="https://user-images.githubusercontent.com/55256366/94050714-44d8b600-fd9c-11ea-80d3-83d59ff00602.png">

**Comment by elihartnett** [comment]
After scrapping version 1.0 of the project and working from 1:20pm to 11:25pm, we finally are back on track. New project is laid out in GitHub how it has to be set up in file directory and opens up a server on the host IP address:5000. Can access by being on same network and going to that address when the program is running. After screenshooting this picture, the formatting issue was also fixed (lines going all the way across screen).

![IMG_0852](https://user-images.githubusercontent.com/55256366/94100871-4766fa00-fdf4-11ea-8404-b2a1a7377a02.png)

**Comment by elihartnett** [comment]
Sheldon added functionality to login and compose an email. Information is printed in console for now. Will connect and implement in next sprint.
