### ISSUE TITLE
Complete the SRS document.

### ISSUE THREAD

**Issue by bkimball98** [Intro-to-SE-Lab-Fall-20/Group-2#5]
Complete the SRS document and submit it.

**Comment by Elliott-Ware** [comment]
We will be sure to have it completed!

**Comment by elihartnett** [comment]
Will review by Friday

**Comment by elihartnett** [comment]
Upon reviewing, I think the format and quality is good. I changed one paragraph indention that was not inline with the rest of the document and that was about it. The only section I was concerned with was section 5 appendix C. I do not have anything to add there, but did not erase it incase anyone else wants to add something there.

**Comment by elihartnett** [comment]
Also went back and added some more definitions.

**Comment by Swaid-design** [comment]
I added a table of contents and fixed some line spacing in the project features section.

**Comment by Swaid-design** [comment]
We finished the SRS document and turned it in.
